In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/conda/lib/python3.11/site-packages/numpy/__init__.py'

## Numpy Arrays (ndarray)

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(matrix[0][2])
print(type(matrix[0][2]))

3
<class 'numpy.int64'>


In [12]:
matrix_d = np.array([[2, 4, 6], [8, 10, 12]], dtype=complex)
matrix_d

array([[ 2.+0.j,  4.+0.j,  6.+0.j],
       [ 8.+0.j, 10.+0.j, 12.+0.j]])

In [13]:
print(type(matrix_d[0][1]))

<class 'numpy.complex128'>


In [16]:
ndarray = np.array([2, 4, 6], dtype=np.uint8)
ndarray

array([2, 4, 6], dtype=uint8)

In [17]:
ndarray = np.array([2, 4, 6], dtype=np.float32)
ndarray

array([2., 4., 6.], dtype=float32)

In [19]:
ndarray = ndarray.astype(np.uint8)
ndarray

array([2, 4, 6], dtype=uint8)