## ndarrayの演算

In [2]:
import numpy as np

In [4]:
ndarray_1 = np.array([[1, 2, 3], [4, 5, 6]])
ndarray_2 = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
print(ndarray_1)
print(ndarray_2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [6]:
ndarray_1 + ndarray_2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
ndarray_1 * ndarray_2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [8]:
ndarray_3 = ([1, 2, 3])
ndarray_1 + ndarray_3

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
ndarray_4 = ([1, 2])
ndarray_1 + ndarray_4

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [10]:
ndarray_1 + 3

array([[4, 5, 6],
       [7, 8, 9]])