In [1]:
import numpy as np

In [2]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [7]:
1e-4

0.0001

In [11]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [18]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [19]:
type(np.where(array > 3))

tuple

In [16]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [14]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [20]:
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [22]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [23]:
(ndarray > 3).all()

np.False_

In [24]:
(ndarray > 3).any()

np.True_

In [25]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [26]:
(ndarray > 3).all(axis=1)

array([False,  True])

In [30]:
array = [1, 1, 2, 3, 4, 4, 5, 6, 6, 1]
np.unique(array)

array([1, 2, 3, 4, 5, 6])

In [31]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([3, 1, 1, 2, 1, 2]))

In [32]:
np.bincount(array)

array([0, 3, 1, 1, 2, 1, 2])