## Indexing, Slicing

In [1]:
import numpy as np

In [2]:
ndarray = np.array([[1, 2, 3], [4, 5, 6]])
ndarray

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
ndarray[1][1]

np.int64(5)

In [7]:
ndarray_1 = np.array(
    [
        [
            [1, 2, 3], [4, 5, 6]
        ], 
        [
            [10, 20, 30], [40, 50, 60]
        ]
    ])
ndarray_1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [9]:
ndarray_1.shape

(2, 2, 3)

In [23]:
ndarray_1[1][1][0]

np.int64(40)

In [29]:
ndarray_1[]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [30]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [31]:
ndarray[1:3]

array([2, 3])

In [33]:
ndarray[:-1]

array([1, 2, 3])

In [34]:
ndarray[1:]

array([2, 3, 4])

In [35]:
ndarray_1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [42]:
ndarray_1[1:]

array([[[10, 20, 30],
        [40, 50, 60]]])

In [53]:
ndarray_1[1:][0]

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
ndarray_1[1:][0][:1]

array([[10, 20, 30]])

In [57]:
ndarray_1[1:][0][:1][0]

array([10, 20, 30])

In [58]:
ndarray_1[1:][0][:1][0][:1]

array([10])

In [59]:
ndarray_1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [66]:
ndarray_1[:1, 0, :2]

array([[1, 2]])

In [69]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
ndarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
ndarray.shape

(4, 3)

In [71]:
ndarray[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [72]:
ndarray[:3][:2]

array([[1, 2, 3],
       [4, 5, 6]])