## np.random

In [1]:
import numpy as np

In [2]:
np.random.rand(3, 4)

array([[0.81600823, 0.12165164, 0.09758712, 0.07970927],
       [0.53837668, 0.52798614, 0.36213319, 0.62452939],
       [0.60945637, 0.70191559, 0.11099485, 0.74590171]])

In [6]:
rng = np.random.default_rng(42)
rng.random((3, 4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [8]:
shape = (3, 4)
rng.random(shape)

array([[0.64386512, 0.82276161, 0.4434142 , 0.22723872],
       [0.55458479, 0.06381726, 0.82763117, 0.6316644 ],
       [0.75808774, 0.35452597, 0.97069802, 0.89312112]])

In [12]:
rng.random(shape)

array([[0.66840296, 0.47109621, 0.56523611, 0.76499886],
       [0.63471832, 0.5535794 , 0.55920716, 0.3039501 ],
       [0.03081783, 0.43671739, 0.21458467, 0.40852864]])

In [13]:
rng = np.random.default_rng(42)
a = rng.random((3, 4))

rng = np.random.default_rng(42)
b = rng.random((3, 4))

print(np.all(a == b))

True


In [17]:
rng = np.random.default_rng(42)
rng.random((3, 4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [16]:
rng = np.random.default_rng(42)
rng.random((3, 4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [18]:
np.random.randn()

-0.20018209482076899

In [24]:
rng = np.random.default_rng(42)
a = rng.standard_normal()
b = rng.standard_normal()
c = rng.standard_normal()

print(a, b, c)

0.30471707975443135 -1.0399841062404955 0.7504511958064572


In [25]:
rng = np.random.default_rng(41)
a = rng.standard_normal()
b = rng.standard_normal()
c = rng.standard_normal()

print(a, b, c)

-1.2316649689147774 0.2671189477208684 -0.006926123563646536


In [27]:
rng = np.random.default_rng()
rng.standard_normal()

-0.7744942394702825

In [28]:
for i in range(30):
    print(rng.standard_normal())

1.9238632464630077
0.1770898126174012
0.5908698953273661
0.8784773045197257
0.9634321911822733
-0.984993650782102
0.09331055174959618
-1.1367724844549445
0.904561403066454
1.029262017611991
-1.1088253138063537
-0.0451822855723882
-0.9629222626276577
0.7679374776247774
0.4564923088457219
0.16500852606859312
0.4936292582696788
1.1524627307836461
0.17835466154217366
1.4502949313768183
-1.0296439273394664
0.9581752723514323
0.4686660819197005
-0.4708651685582665
0.8322572181649356
1.048978768523389
-0.499330572755777
-0.4115687243660167
1.8457152113359874
1.0962430121578084


In [30]:
rng.standard_normal(shape)

array([[ 0.90288923, -0.44155638,  0.29428814,  1.35064675],
       [-0.99089765,  0.88283797, -0.22677823, -0.60919733],
       [-0.97023101, -2.46021459,  0.07157937, -1.32332921]])

In [31]:
rng.standard_normal(shape)

array([[ 1.0097457 , -0.05422696,  0.2766904 ,  0.43198943],
       [-0.26566546,  0.35975754, -0.2749017 ,  0.28710834],
       [ 1.73179668, -0.49237195,  1.24243867, -0.72080331]])

In [32]:
shape = (3, 4, 5)
rng.standard_normal(shape)

array([[[-0.70544762, -1.19864215,  0.4474311 , -0.26014068,
          0.16174567],
        [-0.40910354,  2.09569916,  1.24221864, -0.91382043,
          0.19943129],
        [-1.28944551, -0.16338743, -0.07009654,  0.86374358,
          0.85805735],
        [ 0.01400173, -0.54953722,  0.64205481, -1.78151887,
         -0.82501526]],

       [[-1.00042844, -0.02927462, -1.46560773, -0.60413242,
          0.6777683 ],
        [-0.42162658, -0.30943725,  1.08416954, -0.15658478,
         -0.01642946],
        [-0.31712184, -0.37354636, -0.92104676, -0.88658026,
          1.62134029],
        [ 1.11696809, -1.02827089, -0.65391925,  0.69420991,
          1.10639029]],

       [[ 0.63327833, -2.16767855, -0.59121055,  0.190225  ,
          0.67035696],
        [ 1.04283159, -0.4958033 ,  1.7852345 ,  0.14133966,
         -0.43590166],
        [-1.72802769,  1.24454271,  0.16932268,  0.54400403,
         -2.04553006],
        [-2.14674745, -0.70218632, -1.29765748, -0.05699651,
         -0

In [35]:
rng.normal(10, 1)

9.348257770932184

In [38]:
rng.integers(1, 100, shape)

array([[[56, 85, 74, 86, 56],
        [72, 55,  1, 89, 52],
        [23, 39, 66, 10, 61],
        [86, 90, 50,  7, 13]],

       [[87, 85, 31, 43, 97],
        [41, 44, 45, 32, 39],
        [30, 52, 61,  5, 23],
        [99, 82, 93, 79, 57]],

       [[ 9, 85, 81, 38, 46],
        [34, 63, 32,  2, 42],
        [27,  2, 57, 91, 63],
        [10,  1, 87, 36, 71]]])

In [54]:
index = rng.integers(1, 100, (5, ))
print(index)
print(rng.choice(index))

[24 52 86 98 69]
69
