In [1]:
import numpy as np

In [3]:
rng = np.random.default_rng(42)

In [5]:
ndarray = rng.standard_normal((3, 4, 5))
ndarray

array([[[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472,
         -1.95103519],
        [-1.30217951,  0.1278404 , -0.31624259, -0.01680116,
         -0.85304393],
        [ 0.87939797,  0.77779194,  0.0660307 ,  1.12724121,
          0.46750934],
        [-0.85929246,  0.36875078, -0.9588826 ,  0.8784503 ,
         -0.04992591]],

       [[-0.18486236, -0.68092954,  1.22254134, -0.15452948,
         -0.42832782],
        [-0.35213355,  0.53230919,  0.36544406,  0.41273261,
          0.430821  ],
        [ 2.1416476 , -0.40641502, -0.51224273, -0.81377273,
          0.61597942],
        [ 1.12897229, -0.11394746, -0.84015648, -0.82448122,
          0.65059279]],

       [[ 0.74325417,  0.54315427, -0.66550971,  0.23216132,
          0.11668581],
        [ 0.2186886 ,  0.87142878,  0.22359555,  0.67891356,
          0.06757907],
        [ 0.2891194 ,  0.63128823, -1.45715582, -0.31967122,
         -0.47037265],
        [-0.63887785, -0.27514225,  1.49494131, -0.86583112,
          0

In [6]:
np.save('sample_ndarray', ndarray)

In [8]:
loaded_ndarray = np.load('sample_ndarray.npy')
loaded_ndarray

array([[[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472,
         -1.95103519],
        [-1.30217951,  0.1278404 , -0.31624259, -0.01680116,
         -0.85304393],
        [ 0.87939797,  0.77779194,  0.0660307 ,  1.12724121,
          0.46750934],
        [-0.85929246,  0.36875078, -0.9588826 ,  0.8784503 ,
         -0.04992591]],

       [[-0.18486236, -0.68092954,  1.22254134, -0.15452948,
         -0.42832782],
        [-0.35213355,  0.53230919,  0.36544406,  0.41273261,
          0.430821  ],
        [ 2.1416476 , -0.40641502, -0.51224273, -0.81377273,
          0.61597942],
        [ 1.12897229, -0.11394746, -0.84015648, -0.82448122,
          0.65059279]],

       [[ 0.74325417,  0.54315427, -0.66550971,  0.23216132,
          0.11668581],
        [ 0.2186886 ,  0.87142878,  0.22359555,  0.67891356,
          0.06757907],
        [ 0.2891194 ,  0.63128823, -1.45715582, -0.31967122,
         -0.47037265],
        [-0.63887785, -0.27514225,  1.49494131, -0.86583112,
          0

In [9]:
dict = {
    'id': 123456,
    'image': ndarray
}

In [11]:
np.save('sample_dict.npy', dict)

In [14]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)
loaded_dict

array({'id': 123456, 'image': array([[[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472,
         -1.95103519],
        [-1.30217951,  0.1278404 , -0.31624259, -0.01680116,
         -0.85304393],
        [ 0.87939797,  0.77779194,  0.0660307 ,  1.12724121,
          0.46750934],
        [-0.85929246,  0.36875078, -0.9588826 ,  0.8784503 ,
         -0.04992591]],

       [[-0.18486236, -0.68092954,  1.22254134, -0.15452948,
         -0.42832782],
        [-0.35213355,  0.53230919,  0.36544406,  0.41273261,
          0.430821  ],
        [ 2.1416476 , -0.40641502, -0.51224273, -0.81377273,
          0.61597942],
        [ 1.12897229, -0.11394746, -0.84015648, -0.82448122,
          0.65059279]],

       [[ 0.74325417,  0.54315427, -0.66550971,  0.23216132,
          0.11668581],
        [ 0.2186886 ,  0.87142878,  0.22359555,  0.67891356,
          0.06757907],
        [ 0.2891194 ,  0.63128823, -1.45715582, -0.31967122,
         -0.47037265],
        [-0.63887785, -0.27514225,  1.4949

In [15]:
loaded_dict[()]

{'id': 123456,
 'image': array([[[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472,
          -1.95103519],
         [-1.30217951,  0.1278404 , -0.31624259, -0.01680116,
          -0.85304393],
         [ 0.87939797,  0.77779194,  0.0660307 ,  1.12724121,
           0.46750934],
         [-0.85929246,  0.36875078, -0.9588826 ,  0.8784503 ,
          -0.04992591]],
 
        [[-0.18486236, -0.68092954,  1.22254134, -0.15452948,
          -0.42832782],
         [-0.35213355,  0.53230919,  0.36544406,  0.41273261,
           0.430821  ],
         [ 2.1416476 , -0.40641502, -0.51224273, -0.81377273,
           0.61597942],
         [ 1.12897229, -0.11394746, -0.84015648, -0.82448122,
           0.65059279]],
 
        [[ 0.74325417,  0.54315427, -0.66550971,  0.23216132,
           0.11668581],
         [ 0.2186886 ,  0.87142878,  0.22359555,  0.67891356,
           0.06757907],
         [ 0.2891194 ,  0.63128823, -1.45715582, -0.31967122,
          -0.47037265],
         [-0.63887785, -

In [17]:
ndarray[ndarray>0]

array([0.30471708, 0.7504512 , 0.94056472, 0.1278404 , 0.87939797,
       0.77779194, 0.0660307 , 1.12724121, 0.46750934, 0.36875078,
       0.8784503 , 1.22254134, 0.53230919, 0.36544406, 0.41273261,
       0.430821  , 2.1416476 , 0.61597942, 1.12897229, 0.65059279,
       0.74325417, 0.54315427, 0.23216132, 0.11668581, 0.2186886 ,
       0.87142878, 0.22359555, 0.67891356, 0.06757907, 0.2891194 ,
       0.63128823, 1.49494131, 0.96827835])