## Shape

In [2]:
import numpy as np

In [4]:
ndarray_1 = np.array([1, 2, 3])
ndarray_2 = np.array([[1, 2, 3], [4, 5, 6]])
ndarray_3 = np.array([[1, 2], [4, 5]])

In [8]:
print(ndarray_1.shape)
print(ndarray_2.shape)
print(ndarray_3.shape)

(3,)
(2, 3)
(2, 2)


In [11]:
ndarray_2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
ndarray_2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
ndarray_1.shape

(3,)

In [15]:
ndarray_1 = np.array([[1, 2, 3]])
ndarray_1.shape

(1, 3)

In [18]:
ndarray_1 = np.array([1, 2, 3])
ndarray_2 = np.array([[1, 2, 3]])

print(ndarray_1)
print(ndarray_1.shape)
print(ndarray_2)
print(ndarray_2.shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)


In [17]:
np.expand_dims(ndarray_1, axis=0)

array([[1, 2, 3]])

In [19]:
np.expand_dims(ndarray_1, axis=1)

array([[1],
       [2],
       [3]])

In [20]:
ndarray_1 = np.array([[1, 2, 3], [4, 5, 6]])

print(ndarray_1)
print(ndarray_1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [26]:
expand_ndarray = np.expand_dims(ndarray_1, axis=-1)

print(expand_ndarray)
print(expand_ndarray.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)


In [27]:
np.squeeze(expand_ndarray)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(ndarray)
print(ndarray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [37]:
expand_ndarray = np.expand_dims(ndarray, axis=0)

print(expand_ndarray)
print(expand_ndarray.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)


In [38]:
flat_ndarray = ndarray.flatten()

print(flat_ndarray)
print(flat_ndarray.shape)

[1 2 3 4 5 6 7 8 9]
(9,)


In [41]:
ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ndarray.shape

(3, 3)

In [45]:
expand_ndarray_1 = np.expand_dims(ndarray, axis=0)

print(expand_ndarray_1)
print(expand_ndarray_1.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)


In [46]:
expand_ndarray_2 = np.expand_dims(ndarray, axis=1)

print(expand_ndarray_2)
print(expand_ndarray_2.shape)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
(3, 1, 3)


In [47]:
expand_ndarray_3 = np.expand_dims(ndarray, axis=-1)

print(expand_ndarray_3)
print(expand_ndarray_3.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)
