In [1]:
import numpy as np

In [6]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [5]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [8]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [14]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [12]:
stacked_array = _
stacked_array

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [13]:
stacked_array.shape

(2, 3, 3)

In [19]:
rng = np.random.default_rng(42)
ndarray = rng.standard_normal((3, 4))
ndarray

array([[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259],
       [-0.01680116, -0.85304393,  0.87939797,  0.77779194]])

In [20]:
ndarray.shape

(3, 4)

In [21]:
np.transpose(ndarray)

array([[ 0.30471708, -1.95103519, -0.01680116],
       [-1.03998411, -1.30217951, -0.85304393],
       [ 0.7504512 ,  0.1278404 ,  0.87939797],
       [ 0.94056472, -0.31624259,  0.77779194]])

In [23]:
transpose_ndarray = _
transpose_ndarray.shape

(4, 3)

In [24]:
ndarray.T

array([[ 0.30471708, -1.95103519, -0.01680116],
       [-1.03998411, -1.30217951, -0.85304393],
       [ 0.7504512 ,  0.1278404 ,  0.87939797],
       [ 0.94056472, -0.31624259,  0.77779194]])

In [26]:
ndarray = rng.standard_normal((3, 4, 5))
ndarray.shape

(3, 4, 5)

In [27]:
ndarray.T.shape

(5, 4, 3)